local searchluakeyword = require 'searchluakeyword'
local t = require 'testhelper'

t( searchluakeyword'', {}, t.deepsame )

t( searchluakeyword"do", {['do']={1}}, t.deepsame )
t( searchluakeyword("<<",'s'), {['<<']={1}}, t.deepsame )
t( searchluakeyword"::xxx::", {['::label::']={1}}, t.deepsame )
t( searchluakeyword"::yy::", {['::label::']={1}}, t.deepsame )

t( searchluakeyword"do do", {['do']={1,4}}, t.deepsame )
t( searchluakeyword"dodo", {}, t.deepsame )
t( searchluakeyword"ado", {}, t.deepsame )
t( searchluakeyword"doa", {}, t.deepsame )
t( searchluakeyword"do1", {}, t.deepsame )
t( searchluakeyword"do_", {}, t.deepsame )

t( searchluakeyword("for goto function nil false do and",'i'), {['goto']={5},['function']={10}}, t.deepsame )

t( searchluakeyword"do -- do \n", {['do']={1}}, t.deepsame )
t( searchluakeyword"do -- do \ndo", {['do']={1,11}}, t.deepsame )
t( searchluakeyword"do -- do", {['do']={1}}, t.deepsame )

t( searchluakeyword"do  do  end end", {['do']={1,5},['end']={9,13}}, t.deepsame )
t( searchluakeyword"do 'do' end end", {['do']={1},['end']={9,13}}, t.deepsame )
t( searchluakeyword'do "do" end end', {['do']={1},['end']={9,13}}, t.deepsame )
t( searchluakeyword"do '\"do\"' end end", {['do']={1},['end']={11,15}}, t.deepsame )
t( searchluakeyword'do "\'do\'" end end', {['do']={1},['end']={11,15}}, t.deepsame )
t( searchluakeyword"do [[do]] end end", {['do']={1},['end']={11,15}}, t.deepsame )
t( searchluakeyword"do [=[do]=] end end", {['do']={1},['end']={13,17}}, t.deepsame )
t( searchluakeyword"do [==[do]=] end]==] end", {['do']={1},['end']={22}}, t.deepsame )
t( searchluakeyword"do [[do end end", {['do']={1}}, t.deepsame )

t( searchluakeyword"for", {['for']={1}}, t.deepsame )
t( searchluakeyword"break", {['break']={1}}, t.deepsame )
t( searchluakeyword"goto", {['goto']={1}}, t.deepsame )
t( searchluakeyword"end", {['end']={1}}, t.deepsame )
t( searchluakeyword"while", {['while']={1}}, t.deepsame )
t( searchluakeyword"repeat", {['repeat']={1}}, t.deepsame )
t( searchluakeyword"until", {['until']={1}}, t.deepsame )
t( searchluakeyword"if", {['if']={1}}, t.deepsame )
t( searchluakeyword"then", {['then']={1}}, t.deepsame )
t( searchluakeyword"elseif", {['elseif']={1}}, t.deepsame )
t( searchluakeyword"else", {['else']={1}}, t.deepsame )
t( searchluakeyword"in", {['in']={1}}, t.deepsame )
t( searchluakeyword"function", {['function']={1}}, t.deepsame )
t( searchluakeyword"nil", {['nil']={1}}, t.deepsame )
t( searchluakeyword"false", {['false']={1}}, t.deepsame )
t( searchluakeyword"true", {['true']={1}}, t.deepsame )
t( searchluakeyword"and", {['and']={1}}, t.deepsame )
t( searchluakeyword"or", {['or']={1}}, t.deepsame )
t( searchluakeyword"not", {['not']={1}}, t.deepsame )
t( searchluakeyword(';'  ,'s'), {[';'  ]={1}}, t.deepsame )
t( searchluakeyword('{'  ,'s'), {['{'  ]={1}}, t.deepsame )
t( searchluakeyword('{'  ,'s'), {['{'  ]={1}}, t.deepsame )
t( searchluakeyword('}'  ,'s'), {['}'  ]={1}}, t.deepsame )
t( searchluakeyword('['  ,'s'), {['['  ]={1}}, t.deepsame )
t( searchluakeyword(']'  ,'s'), {[']'  ]={1}}, t.deepsame )
t( searchluakeyword('...','s'), {['...']={1}}, t.deepsame )
t( searchluakeyword('('  ,'s'), {['('  ]={1}}, t.deepsame )
t( searchluakeyword(')'  ,'s'), {[')'  ]={1}}, t.deepsame )
t( searchluakeyword(':'  ,'s'), {[':'  ]={1}}, t.deepsame )
t( searchluakeyword('.'  ,'s'), {['.'  ]={1}}, t.deepsame )
t( searchluakeyword('='  ,'s'), {['='  ]={1}}, t.deepsame )
t( searchluakeyword('+'  ,'s'), {['+'  ]={1}}, t.deepsame )
t( searchluakeyword('-'  ,'s'), {['-'  ]={1}}, t.deepsame )
t( searchluakeyword('*'  ,'s'), {['*'  ]={1}}, t.deepsame )
t( searchluakeyword('/'  ,'s'), {['/'  ]={1}}, t.deepsame )
t( searchluakeyword('//' ,'s'), {['//' ]={1}}, t.deepsame )
t( searchluakeyword('^'  ,'s'), {['^'  ]={1}}, t.deepsame )
t( searchluakeyword('%'  ,'s'), {['%'  ]={1}}, t.deepsame )
t( searchluakeyword('&'  ,'s'), {['&'  ]={1}}, t.deepsame )
t( searchluakeyword('~'  ,'s'), {['~'  ]={1}}, t.deepsame )
t( searchluakeyword('|'  ,'s'), {['|'  ]={1}}, t.deepsame )
t( searchluakeyword('>>' ,'s'), {['>>' ]={1}}, t.deepsame )
t( searchluakeyword('<<' ,'s'), {['<<' ]={1}}, t.deepsame )
t( searchluakeyword('..' ,'s'), {['..' ]={1}}, t.deepsame )
t( searchluakeyword('<'  ,'s'), {['<'  ]={1}}, t.deepsame )
t( searchluakeyword('<=' ,'s'), {['<=' ]={1}}, t.deepsame )
t( searchluakeyword('>'  ,'s'), {['>'  ]={1}}, t.deepsame )
t( searchluakeyword('>=' ,'s'), {['>=' ]={1}}, t.deepsame )
t( searchluakeyword('==' ,'s'), {['==' ]={1}}, t.deepsame )
t( searchluakeyword('~=' ,'s'), {['~=' ]={1}}, t.deepsame )
t( searchluakeyword('-'  ,'s'), {['-'  ]={1}}, t.deepsame )
t( searchluakeyword('#'  ,'s'), {['#'  ]={1}}, t.deepsame )

t()

