--[===[DOC

= countiter

[source,lua]
----
local function countiter( ... ) --> countInt
----

Count the number of iteration generated by a iterator. The argument must be the
same varargs a `for in` loop. It will return the number of iteration.

E.g. `countiter(pairs(tab))` will count the number of key in the table `tab`.

]===]

local function countiter( ... ) --> countInt
  local countInt = 0
  if select('#', ...) ~= 0 then
    for _ in ... do
      countInt = countInt + 1
    end
  end
  return countInt
end

return countiter